apiVersion: v2
name: raw-spans-grouper
description: Raw Spans Grouper

type: application

version: 0.1.0

dependencies:
  - name: kafka-topic-creator
    repository: "https://storage.googleapis.com/hypertrace-helm-charts"
    version: 0.2.x
    condition: kafka-topic-creator.enabled
