version: 2.1

orbs:
  codecov: codecov/codecov@1
  snyk: snyk/snyk@0.0.10

executors:
  gradle_docker:
    docker:
      - image: cimg/openjdk:11.0
  helm:
    docker:
      - image: hypertrace/helm-gcs-packager:0.3.0

commands:
  gradle:
    description: 'Run the provided gradle command'
    parameters:
      args:
        type: string
      when:
        default: "on_success"
        type: enum
        enum: ["on_fail", "on_success", "always"]
    steps:
      - run:
          name: << parameters.args >>
          command: ./gradlew << parameters.args >> --info --max-workers=2 -Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.console=plain --continue
          when: << parameters.when >>
  update-submodule:
    description: 'Pull Submodules'
    steps:
      - run:
          name: Pull Submodules
          command: git submodule update --init --recursive
      - run:
          name: Ensure submodules point to commit from main branch
          command: git submodule foreach "git merge-base --is-ancestor HEAD origin/main"
  setup_build_environment:
    description: 'Generates cache key from a hash of all gradle files'
    steps:
      - checkout
      - update-submodule
      - run:
          name: Generate cache key
          command: find . -type f -name "*.gradle*" -o -name "gradle-wrapper*" -exec shasum {} + | sort > /tmp/checksum.txt && cat /tmp/checksum.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/checksum.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  populate_and_save_cache:
    description: 'Downloads all gradle dependencies and uploads cache for later use'
    steps:
      - gradle:
          args: downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "/tmp/checksum.txt" }}
jobs:
  build:
    executor: gradle_docker
    steps:
      - setup_build_environment
      - setup_remote_docker: &latest_remote_docker
          version: 19.03.12
      - populate_and_save_cache
      - gradle:
          args: build dockerBuildImages
      - gradle:
          args: jacocoTestReport
      - codecov/upload:
          flags: unit
  publish:
    executor: gradle_docker
    steps:
      - setup_build_environment
      - setup_remote_docker: *latest_remote_docker
      - gradle:
          args: :tag -Prelease
      - add_ssh_keys:
          fingerprints:
            - '76:7a:c8:91:c0:cd:eb:71:96:3c:44:c6:cf:b0:26:83'
      - run: git push origin $(./gradlew -q :printVersion)
      - gradle:
          args: dockerPushImages
  validate-charts:
    executor: helm
    steps:
      - checkout
      - run:
          name: Helm Charts Lint and Template Render
          command: |
            .circleci/helm.sh validate
  snyk-scan:
    executor:
      name: gradle_docker
    environment:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 # Snyk doesn't handle parallelism well
    steps:
      - setup_build_environment
      - snyk/scan:
          additional-arguments: --all-sub-projects --policy-path=.snyk
  package-charts:
    executor: helm
    steps:
      - checkout
      - run:
          name: Package and Publish Helm Charts
          command: |
            .circleci/helm.sh package
            .circleci/helm.sh publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - validate-charts
      - snyk-scan:
          context: hypertrace-vulnerability-scanning
      - publish:
          context: hypertrace-publishing
          requires:
            - build
            - validate-charts
            - snyk-scan
          filters:
            branches:
              only:
                - main
      - package-charts:
          context: hypertrace-publishing
          requires:
            - publish
          filters:
            branches:
              only:
                - main
